repos:
- repo: https://gitee.com/SWHL/autoflake
  rev: v2.1.1
  hooks:
    - id: autoflake
      args:
        [
          "--recursive",
          "--in-place",
          "--remove-all-unused-imports",
          "--ignore-init-module-imports",
        ]
      files: \.py$
- repo: https://gitee.com/SWHL/black
  rev: 23.1.0
  hooks:
    - id: black
      files: \.py$